dist: trusty
sudo: required

# branches:
#   only:
#   - master

os:
  - linux

# in theory travis should detect what to install,
# but we use meson, which is not supported by travis yet and we need custom commands
compiler:
  - gcc

language:
  - c

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET=linux-i386
    - os: linux
      dist: trusty
      env: TARGET=linux-amd64
    - os: linux
      dist: trusty
      env: TARGET=linux-armv7hl
    - os: linux
      dist: trusty
      env: TARGET=win-x86
    - os: linux
      dist: trusty
      env: TARGET=win-x64

before_install:
  # show some extra info
  - export | sort
  - env | sort
  # update base distro
  - sudo apt-get update
  # - sudo apt-get -y upgrade
  # - sudo apt-get -y dist-upgrade
  # install base packages
  - sudo apt-get -y install build-essential python-virtualenv python3-dev python3-pip ninja-build cmake gcc-multilib
  # ensure we do not have curl dev libs, otherwise it caused cross compilations to fail
  - sudo apt-get -y remove libcurl.*-dev
  # install cross complier if we gonna do binaries for windows
  - if [ -z "${TARGET##*win*}" ]; then sudo apt-get -y install mingw-w64 ; fi
  # install cross compiler tools if we gonna do binares for arm/raspberry
  # notice it will remove gcc-multilib
  - if [ -z "${TARGET##*arm*}" ]; then sudo apt-get -y install gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf ;fi
  # activate virtualenv with python3, meson requires python3
  - virtualenv .venv --python=python3
  - . .venv/bin/activate
  - pip3 install --upgrade pip
  # install python packages like meson, ninja etc...
  - pip3 install -r requirements.txt

# each script section is executed in matrix build
script:
  - mkdir build_${TARGET} || true
  - meson build_${TARGET} --cross-file cross-compilation_${TARGET}.txt
  - ninja -v -C build_${TARGET}
  # print basic info about complied files
  - find build_${TARGET}/ -type f -name "mvdsv*" -exec file {} \;


